# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghapp < Formula
  desc "GitHub App authentication for git and gh"
  homepage "https://github.com/operator-kit/ghapp-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/operator-kit/ghapp-cli/releases/download/v0.1.0/ghapp_0.1.0_darwin_amd64.tar.gz"
      sha256 "8cf62029b3dcc2512fe0f80c4a3b29d228ed59e10bfba2bbbdbb3d7fbe1b6bba"

      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/operator-kit/ghapp-cli/releases/download/v0.1.0/ghapp_0.1.0_darwin_arm64.tar.gz"
      sha256 "239b70255cedacae6cad813f5f67893809ac9727117ef479861c4e2e0b099678"

      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/operator-kit/ghapp-cli/releases/download/v0.1.0/ghapp_0.1.0_linux_amd64.tar.gz"
      sha256 "e7c921d1230e527eb43fbfc503a719a14f6d93b2679c5e69b8f3847b91b0a745"
      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/operator-kit/ghapp-cli/releases/download/v0.1.0/ghapp_0.1.0_linux_arm64.tar.gz"
      sha256 "01fc73778e976db26e276bdc60010050c714f097e7d3806700644e66103de593"
      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
  end

  test do
    system "#{bin}/ghapp", "version"
  end
end
