# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghapp < Formula
  desc "GitHub App authentication for git and gh"
  homepage "https://github.com/operator-kit/ghapp-cli"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/operator-kit/ghapp-cli/releases/download/v0.1.1/ghapp_0.1.1_darwin_amd64.tar.gz"
      sha256 "1a60d830bc1c430a8ca7e91ed8ecf5493f053ca7524023ef8cf020cb8335170e"

      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/operator-kit/ghapp-cli/releases/download/v0.1.1/ghapp_0.1.1_darwin_arm64.tar.gz"
      sha256 "c6ff2a80c9b477cc910e842d855b64245a23f5fa36fab7e26d785ccb1680034c"

      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/operator-kit/ghapp-cli/releases/download/v0.1.1/ghapp_0.1.1_linux_amd64.tar.gz"
      sha256 "b4bb540bed6a8814a8c43c16cf614c2675067fc94fe2f7ef08c1a654e4c00514"
      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/operator-kit/ghapp-cli/releases/download/v0.1.1/ghapp_0.1.1_linux_arm64.tar.gz"
      sha256 "795e227b03e6853a6b4cb530b6a0d998027d77aa64a55e4830b75d4f6fbdc5a6"
      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
  end

  test do
    system "#{bin}/ghapp", "version"
  end
end
