# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghapp < Formula
  desc "GitHub App authentication for git and gh"
  homepage "https://github.com/operator-kit/ghapp-cli"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/operator-kit/ghapp-cli/releases/download/v0.1.1/ghapp_0.1.1_darwin_amd64.tar.gz"
      sha256 "fec26c911edd54d9500a4206471dd12cd7bde010e323485d05f9dfbd02dd1522"

      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/operator-kit/ghapp-cli/releases/download/v0.1.1/ghapp_0.1.1_darwin_arm64.tar.gz"
      sha256 "1916cc95a61bb28b11f4a1425867c7c4568687bded15995577004305e0d688ba"

      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/operator-kit/ghapp-cli/releases/download/v0.1.1/ghapp_0.1.1_linux_amd64.tar.gz"
      sha256 "7fb62fa0882b1aad46b3ffca23b99d2e4ab4364dbcb57d347c1c8bdb5a0d59c8"
      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/operator-kit/ghapp-cli/releases/download/v0.1.1/ghapp_0.1.1_linux_arm64.tar.gz"
      sha256 "ac21f6c1b1c22904c21f9bda8f305258c3872b08b8c3c469d1485b9e2b534881"
      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
  end

  test do
    system "#{bin}/ghapp", "version"
  end
end
