# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubAppAuth < Formula
  desc "GitHub App authentication for git and gh"
  homepage "https://github.com/operator-kit/github-app-auth"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/operator-kit/github-app-auth/releases/download/v0.1.2/github-app-auth_0.1.2_darwin_amd64.tar.gz"
      sha256 "f13fbd4b8566128ac955aebcf5cffbf6dc3f79c5d1cf27ac61b0347eef919850"

      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/operator-kit/github-app-auth/releases/download/v0.1.2/github-app-auth_0.1.2_darwin_arm64.tar.gz"
      sha256 "3b3a248db78ec6c6d56df080bdb1a3b609dd4d06609374325af90e9b1d9f4c5b"

      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/operator-kit/github-app-auth/releases/download/v0.1.2/github-app-auth_0.1.2_linux_amd64.tar.gz"
      sha256 "cb5139f8a1cdd1b5922cd9ffd89c7e5211dd4a1ae780afb7c3f03725f6c74aed"
      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/operator-kit/github-app-auth/releases/download/v0.1.2/github-app-auth_0.1.2_linux_arm64.tar.gz"
      sha256 "1b711fcc2ae1304b4d4a0063883a6a50226cf7d696239b30151f4018efab57d6"
      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
  end

  test do
    system "#{bin}/ghapp", "version"
  end
end
