# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubAppAuth < Formula
  desc "GitHub App authentication for git and gh"
  homepage "https://github.com/operator-kit/github-app-auth"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/operator-kit/github-app-auth/releases/download/v0.1.1/github-app-auth_0.1.1_darwin_amd64.tar.gz"
      sha256 "f759c7724dcaaa4d723b7a301bb9cbe0f7a5586faf8f75bc7a0e38b424485697"

      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/operator-kit/github-app-auth/releases/download/v0.1.1/github-app-auth_0.1.1_darwin_arm64.tar.gz"
      sha256 "1a310a287fbd5fe2c9b4eeb061b85f50ef7929bc66c33c6d1dbf7587b35b22b5"

      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/operator-kit/github-app-auth/releases/download/v0.1.1/github-app-auth_0.1.1_linux_amd64.tar.gz"
      sha256 "0ba16296e34092bc0627e992608dca529dbca3cdbff1ddc1a03d72b3b599fe4f"
      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/operator-kit/github-app-auth/releases/download/v0.1.1/github-app-auth_0.1.1_linux_arm64.tar.gz"
      sha256 "2ae03faa9884befc8b41439a339fe4aab0fca12a449e3ab190a544d908d0ce60"
      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
  end

  test do
    system "#{bin}/ghapp", "version"
  end
end
