# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubAppAuth < Formula
  desc "GitHub App authentication for git and gh"
  homepage "https://github.com/operator-kit/github-app-auth"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/operator-kit/github-app-auth/releases/download/v0.1.0/github-app-auth_0.1.0_darwin_amd64.tar.gz"
      sha256 "d722a03db8a05eca34fec78e227047177d57c4ddfe74a8b97267c563edc04d2d"

      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/operator-kit/github-app-auth/releases/download/v0.1.0/github-app-auth_0.1.0_darwin_arm64.tar.gz"
      sha256 "121c13f8a870d26828c0581160a65441d177817db18f22529e9fe30a409b0a8a"

      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/operator-kit/github-app-auth/releases/download/v0.1.0/github-app-auth_0.1.0_linux_amd64.tar.gz"
      sha256 "220936901f18e79fe2a48f35df66bbf98b4a31f1c8e83934b2d3cacc60beeee7"
      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/operator-kit/github-app-auth/releases/download/v0.1.0/github-app-auth_0.1.0_linux_arm64.tar.gz"
      sha256 "b6b8a249d5f5e3d57c4a54f1549ffa0889916be47a98b533476c11b735a9e5ea"
      define_method(:install) do
        bin.install "ghapp"
        bin.install "ghapp-gh"
      end
    end
  end

  test do
    system "#{bin}/ghapp", "version"
  end
end
