# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hs < Formula
  desc "HelpScout CLI — manage mailboxes, conversations, customers and more"
  homepage "https://github.com/operator-kit/hs-cli"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/operator-kit/hs-cli/releases/download/v0.2.0/hs_0.2.0_darwin_amd64.tar.gz"
      sha256 "80c913b5d0441a5e0ff9217d6d68f4f634e4a7ec6aa06583d05ad3a809e2f0eb"

      define_method(:install) do
        bin.install "hs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/operator-kit/hs-cli/releases/download/v0.2.0/hs_0.2.0_darwin_arm64.tar.gz"
      sha256 "3a99a880e9a87e42965b83c96ed75d1ce01fe42fb143a6fb3bb0c667325207b1"

      define_method(:install) do
        bin.install "hs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/operator-kit/hs-cli/releases/download/v0.2.0/hs_0.2.0_linux_amd64.tar.gz"
      sha256 "b1627b8b8926ee85a9d930f513355b9af5a120d44eb975c5c4090706373cd383"
      define_method(:install) do
        bin.install "hs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/operator-kit/hs-cli/releases/download/v0.2.0/hs_0.2.0_linux_arm64.tar.gz"
      sha256 "df9cf71835c7f0a0b073144bb592cadb5d944ebc933a0df919d576635854126c"
      define_method(:install) do
        bin.install "hs"
      end
    end
  end

  test do
    system "#{bin}/hs", "version"
  end
end
