# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hs < Formula
  desc "HelpScout CLI — manage mailboxes, conversations, customers and more"
  homepage "https://github.com/operator-kit/hs-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/operator-kit/hs-cli/releases/download/v0.1.0/hs_0.1.0_darwin_amd64.tar.gz"
      sha256 "eeaec6a7ac588b2390151b7e5e9b21eabfea5745a54115c3f1331ed160b79288"

      define_method(:install) do
        bin.install "hs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/operator-kit/hs-cli/releases/download/v0.1.0/hs_0.1.0_darwin_arm64.tar.gz"
      sha256 "f32313161257f866548cd8a5c69fe53f062a0cd27b3c9a06d5ec70c5a1107996"

      define_method(:install) do
        bin.install "hs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/operator-kit/hs-cli/releases/download/v0.1.0/hs_0.1.0_linux_amd64.tar.gz"
      sha256 "d1b1d8cba8bc38361756c61a65cbcf8aeaf6e1ed87a22181cfb788c932924b05"
      define_method(:install) do
        bin.install "hs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/operator-kit/hs-cli/releases/download/v0.1.0/hs_0.1.0_linux_arm64.tar.gz"
      sha256 "f5accc8a8f4067454db6bf4537ab8df03e118cf292a0766a26089c652040780a"
      define_method(:install) do
        bin.install "hs"
      end
    end
  end

  test do
    system "#{bin}/hs", "version"
  end
end
