# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hs < Formula
  desc "HelpScout CLI — manage mailboxes, conversations, customers and more"
  homepage "https://github.com/operator-kit/hs-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/operator-kit/hs-cli/releases/download/v0.1.0/hs_0.1.0_darwin_amd64.tar.gz"
      sha256 "e9878b93b6c1407ff65aa30f30307ad98ec40aaa4397765995800754eea15194"

      define_method(:install) do
        bin.install "hs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/operator-kit/hs-cli/releases/download/v0.1.0/hs_0.1.0_darwin_arm64.tar.gz"
      sha256 "45b0f9938871d0cfaaa674e6a2ab191ebc874e69f960a2fa135ce9e8d80277ad"

      define_method(:install) do
        bin.install "hs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/operator-kit/hs-cli/releases/download/v0.1.0/hs_0.1.0_linux_amd64.tar.gz"
      sha256 "741775255c8db4909b4f87d817441d2bcf19a3337899ca4449cd97bec05668ff"
      define_method(:install) do
        bin.install "hs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/operator-kit/hs-cli/releases/download/v0.1.0/hs_0.1.0_linux_arm64.tar.gz"
      sha256 "bc63b9cda8a6dae8a28ffbefaa2b6edf4623851df5d02097e33ed46b116157a6"
      define_method(:install) do
        bin.install "hs"
      end
    end
  end

  test do
    system "#{bin}/hs", "version"
  end
end
